AnimaliaV2-master/AnimaliaV2/Controllers/AccesoController.cs
using AnimaliaV2.Models;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using AnimaliaV2.Data;
using MySql.Data.MySqlClient;

namespace AnimaliaV2.Controllers
{
    public class AccesoController : Controller
    {

        public readonly AccesoManejador _manejadorAcceso;

        public AccesoController(MySqlConnection connection)
        {
            _manejadorAcceso = new AccesoManejador(connection);
        }

        [HttpPost] 
        public async Task<IActionResult> Index(UsuarioModel a)
        {
            
            var usuario = _manejadorAcceso.validarUsuario(a.nombreUsuario,a.contraseniaUsuario);

            if (usuario != null)
            {
                var clains = new List<Claim>();
                clains.Add(new Claim(ClaimTypes.Role,usuario.fk_idRol.ToString()));
                clains.Add(new Claim(ClaimTypes.Name, usuario.nombreUsuario.ToString()));
                clains.Add(new Claim("idUsuario", usuario.idUsuario.ToString(), ClaimValueTypes.String));
                //clains.Add(new Claim("NombreUsuario", usuario.nombreUsuario.ToString(), ClaimValueTypes.String));

                var clainsIdentity = new ClaimsIdentity(clains, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(clainsIdentity));

                return RedirectToAction("Index", "Home");


            }   else{
                TempData["Message"] = "Por favor, verifica tu USUARIO y CONTRASENA";
                return RedirectToAction("IniciarSesion", "Invitado");
            }


        }



        public async Task<IActionResult> Salir()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Invitado");
        }


    }
}

AnimaliaV2-master/AnimaliaV2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Animalia</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" />
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' asp-append-version="true" />
    <link rel="stylesheet" href="~/css/estiloProyecto.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/swiper-bundle.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Animalia.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.4/dist/sweetalert2.min.css">
</head>
<body>
    <div class="layout">
        <div class="logo-detalle">
            <div class="logo-nombre">ANIMALIA</div>
            <i class='bx bx-chevrons-right' id="btn"></i>
        </div>
        <ul class="lista-navegacion">
            @*Opciones de invitado*@
            @if (!User.IsInRole("1") && !User.IsInRole("2"))
            {
          

                <li>
                    <a asp-controller="Invitado" asp-action="Index">
                        <i class='bx bx-grid-alt'></i>
                        <!-- Este inicio es para los que no han iniciado sesion -->
                        <span class="nombre_link">Inicio</span>
                    </a>
                    <span class="titulos">Inicio</span>
                </li>

                <li>
                    <a asp-action="vermascotas" asp-controller="Invitado">
                        <i class='bx bxs-dog'></i>
                        <span class="nombre_link">Ver mascotas</span>
                    </a>
                    <span class="titulos">Ver mascotas</span>
                </li>

                <li>
                    <a asp-action="quienesSomos" asp-controller="Invitado">
                        <i class="bi bi-search-heart-fill"></i>
                        <span class="nombre_link">¿Quienes somos?</span>
                    </a>
                    <span class="titulos">¿Quienes somos?</span>
                </li>
            }
               
            @if (User.IsInRole("1") || User.IsInRole("2"))
            {

                <li>
                    <a asp-controller="Home" asp-action="Index">
                        <i class='bx bx-grid-alt'></i>
                        <span class="nombre_link">Pagina principal</span>
                    </a>
                    <span class="titulos">Pagina principal</span>
                </li>
                
            }
            
            @if (User.IsInRole("1"))
            {
                <li>
                    <a asp-action="gestionarPersonas" asp-controller="Persona">
                        <i class='bx bx-user'></i>
                        <span class="nombre_link">Gestionar personas</span>
                    </a>
                    <span class="titulos">Gestionar personas</span>
                </li>

                <li>
                    <a asp-action="gestionarMascotas" asp-controller="Mascotas">
                        <i class='bx bxs-cat'></i>
                        <span class="nombre_link">Gestionar mascotas</span>
                    </a>
                    <span class="titulos">Gestionar mascotas</span>
                </li>

              

                <li>
                    <a asp-action="permisos" asp-controller="Home">
                        <i class='bx bx-cog'></i>
                        <span class="nombre_link">Permisos</span>
                    </a>
                    <span class="titulos">Permisos</span>
                </li>
            }

            
            
            <!-- hasta aqui van los elementos del admin -->
            @if (User.IsInRole("2"))
            {
                <li>
                    <a asp-action="registrarMascota" asp-controller="Mascotas">
                        <i class="bi bi-browser-firefox"></i>
                        <span class="nombre_link">Registrar mascota</span>
                    </a>
                    <span class="titulos">Registrar mascota</span>
                </li>

                <li>
                    <a asp-action="verMascotas" asp-controller="Mascotas">
                        <i class='bx bx-search-alt'></i>
                        <span class="nombre_link">Ver mascotas</span>
                    </a>
                    <span class="titulos">Ver mascotas</span>
                </li>

                <li>
                    <a asp-action="solicitudes" asp-controller="Persona">
                        <i class='bx bxs-envelope'></i>
                        <span class="nombre_link">Mis solicitudes</span>
                    </a>
                    <span class="titulos">Mis solicitudes</span>
                </li>

            }
             @if (User.IsInRole("1") || User.IsInRole("2"))
            {
                <li>
                    <a asp-action="ModificarPersona" asp-controller="Persona">
                        <i class='bx bxs-universal-access'></i>
                        <span class="nombre_link">Actualizar datos</span>
                    </a>
                    <span class="titulos">Actualizar datos</span>
                </li>
            <li>
                <a asp-action="reportes" asp-controller="Home">
                    <i class='bx bxs-receipt'></i>
                    <span class="nombre_link">Reportes</span>
                </a>
                <span class="titulos">Reportes</span>
            </li>
            }
            @if (User.IsInRole("1") || User.IsInRole("2"))
            {
                <li class="perfil">
                    <div class="perfil-detalles">
                        <div class="nombre_trabajo">
                            <div class="nombre">@User.Identity.Name</div>
                            @if (User.IsInRole("1"))
                            {
                                <div class="trabajo">Administrador</div>
                            }
                            else{
                                <div class="trabajo">Cliente</div>
                            }
                            </div>
                    </div>
                    <a asp-action="Salir" asp-controller="Acceso"><i class='bx bx-log-out' id="log_out"></i></a>
                </li>
            }

            
           
        </ul>
    </div>

    <div class="seccion-principal">
        
            @RenderBody()
       
    </div>

    <footer>
        <ul class="footer-menu-contenedor">
            <b></b>
            <li class="item-menu"><b>Contacto: </b></li>
            <li class="item-menu">
                <a target="_blank" id="contacto" 
                    href="https://wa.link/51ua5q">j.cortaza@udla.edu.co <i class="bi bi-whatsapp"></i></a>
            </li>
            <li class="item-menu"><b>-</b></li>
            <li class="item-menu">
                <a target="_blank" id="contacto"
                   href="https://wa.link/rwu4m1">andre.narvaez@udla.edu.co <i class="bi bi-whatsapp"></i></a>
            </li>
        </ul>
        <ul class="footer-menu-contenedor">
            <b></b>
            <li class="item-menu"><b>2023</b></li>
            <li class="item-menu"><b>-</b></li>
            <li class="item-menu"><b>Todos los derechos reservados</b></li>
            <li class="item-menu"><b>-</b></li>
            <li class="item-menu"><b>Universidad de la Amazonia</b></li>
        </ul>
        <a href="#" class="copyright">¿Quienes somos?</a>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/js/jsEspecieRaza.js" asp-append-version="true"></script>
    <script src="~/js/jsDepartamentoMunicipio.js" asp-append-version="true"></script>
    <script src="~/js/jsTablasDinamicas.js" asp-append-version="true"></script>
    <script src="~/js/jsTablasJSONs.js" asp-append-version="true"></script>
    <script src="~/js/swiper-bundle.min.js" asp-append-version="true"></script>
    <script src="~/js/jsSwiper.js" asp-append-version="true"></script>
    <script src="~/js/jsPrincipal.js" asp-append-version="true"></script>
    <script src="~/js/jsAcordeon.js" asp-append-version="true"></script>
    <script src="~/js/validarUsuario.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.1.4/dist/sweetalert2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>