AnimaliaV2-master/AnimaliaV2/Controllers/PersonaController.cs
using AnimaliaV2.Data;
using AnimaliaV2.Models;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using System.Collections.Generic;
using System.Security.Claims;

namespace AnimaliaV2.Controllers
{
    public class PersonaController : Controller
    {
        public readonly PersonaManejador _personaManejador;

        public PersonaController(MySqlConnection connection)
        {
            _personaManejador = new PersonaManejador(connection);
        }
        public IActionResult misSolicitudes()
        {
            ClaimsPrincipal currentUser = this.User;
            Claim idUsuarioClaim = currentUser.FindFirst("idUsuario");
            int idUsuario = Convert.ToInt32(idUsuarioClaim?.Value);
            List<SolicitudAdopcionViewModel> list = _personaManejador.listarmisSolicitudes(idUsuario);
            return View(list);
        }

        [HttpPost]
        public IActionResult eliminarSolicitud(int id)
        {

            _personaManejador.EliminarSolicitud(id);
            return RedirectToAction("misSolicitudes");
        }

        public IActionResult GestionarSolicitudes()
        {
            ClaimsPrincipal currentUser = this.User;
            Claim idUsuarioClaim = currentUser.FindFirst("idUsuario");
            int idUsuario = Convert.ToInt32(idUsuarioClaim?.Value);
            List<GestionarSolicitudViewModel> list = _personaManejador.gestionar_solicitudes(idUsuario);
            return View(list);
        }

        [HttpPost]
        public IActionResult denegarSolicitud(int id_denegar)
        {
            _personaManejador.denegarSolicitud(id_denegar);
            return RedirectToAction("GestionarSolicitudes");
        }

        [HttpPost]
        public IActionResult AprobarSolicitud(int id_aprobar, int id_mascota)
        {
            _personaManejador.AprobarSolicitud(id_aprobar, id_mascota);
            return RedirectToAction("GestionarSolicitudes");
        }

        public IActionResult GestionarDonaciones()
        {
            ClaimsPrincipal currentUser = this.User;
            Claim idUsuarioClaim = currentUser.FindFirst("idUsuario");
            int idUsuario = Convert.ToInt32(idUsuarioClaim?.Value);
            List<GestionAdopcionViewModel> list = _personaManejador.gestionar_donaciones(idUsuario);
            return View(list);
        }

        [HttpPost]
        public IActionResult eliminar_solicitud_adopcion(int id_solicitud, int id_mascota)
        {
            _personaManejador.eliminar_adopcion(id_solicitud, id_mascota);
            return RedirectToAction("GestionarDonaciones");
        }

        [HttpPost]
        public IActionResult donarMascota(int id_solicitud, int id_mascota)
        {
            _personaManejador.donarMascota(id_solicitud, id_mascota);
            return RedirectToAction("GestionarDonaciones");
        }

        public IActionResult misMascotas()
        {
            ClaimsPrincipal currentUser = this.User;
            Claim idUsuarioClaim = currentUser.FindFirst("idUsuario");
            int idUsuario = Convert.ToInt32(idUsuarioClaim?.Value);
            List<MisMascotasModel> list = _personaManejador.misMascotas(idUsuario);
            return View(list);
        }
        public IActionResult EliminarMascota(int id_mascota)
        {
            _personaManejador.EliminarMascota(id_mascota);
            return RedirectToAction("misMascotas");
        }
        public IActionResult ModificarPersona()
        {
            ClaimsPrincipal currentUser = this.User;
            Claim idUsuarioClaim = currentUser.FindFirst("idUsuario");
            int idUsuario = Convert.ToInt32(idUsuarioClaim?.Value);
            PersonaModel list = _personaManejador.ConsultarPersona(idUsuario);
            return View(list);
        }

        [HttpPost]
        public IActionResult ModificarPersona(PersonaModel persona)
        {
            _personaManejador.ModificarPersona(persona);
            return RedirectToAction("ModificarPersona");
        }
        public IActionResult ListadoPersonas()
        { 
            List<PersonaModel> list = _personaManejador.ListadoPersonas();
            return View(list);
        }

       
        public IActionResult EditarPersona(int id_persona)
        {
            PersonaModel list = _personaManejador.ConsultarIdPersona(id_persona);
            return View(list);
        }

        [HttpPost]
        public IActionResult Editar_Persona(PersonaModel persona)
        {
            _personaManejador.EditarPersona(persona);
            return RedirectToAction("ListadoPersonas");
        }

        public IActionResult listadoUsuarios()
        {
            List<UsuarioViewModel> list = _personaManejador.ListadoUsuarios();
            return View(list);
        }

        [HttpGet]
        public IActionResult Modificar_Usuario(int id_usuario)
        {
            UsuarioViewModel list = _personaManejador.ConsultarUsuario(id_usuario);
            return View(list);
        }

        [HttpPost]
        public IActionResult Modificar_Usuario(UsuarioModel user_)
        {
            _personaManejador.EditarUsuario(user_);
            return RedirectToAction("listadoUsuarios");
        }

        public IActionResult Eliminar_Usuario(int id_usuario)
        {
            _personaManejador.Eliminar_Usuario(id_usuario);
            return RedirectToAction("listadoUsuarios");
        }
        public IActionResult solicitudes()
        {

            return View();
        }


        public IActionResult gestionarPersonas()
        {

            return View();
        }
    }
}

AnimaliaV2-master/AnimaliaV2/Views/Persona/EditarPersona.cshtml
@model PersonaModel
@{
    ViewData["Title"] = "Editar Persona";

}
<div id="inicioTitulo">
    <h1 id="tituloInicio" class="titulopersona">DATOS PERSONALES</h1>
</div>
<form method="post" asp-action="Editar_Persona" asp-controller="Persona">
    <div id="displayflex">
        <div id="display">
            <input type="hidden" asp-for="idPersona" value="@Model.idPersona">
            <label>Número de Documento:</label>
            <input type="text" class="opacity" readonly value="@Model.documentoPersona">
            <label>Segundo Nombre:</label>
            <input type="text" class="opacity" placeholder="Opcional" readonly value="@Model.snombrePersona">
            <label>Segundo Apellido:</label>
            <input type="text" class="opacity" placeholder="Opcional" readonly value="@Model.sapellidoPersona">
            <label>Dirección:</label>
            <input type="text" class="opacity" readonly value="@Model.direcccion">
            <label>Teléfono:</label>
            <input type="text" class="opacity" readonly value="@Model.telefono">
        </div>
        <div id="display">
            <label>Primer Nombre:</label>
            <input type="text" class="opacity" readonly value="@Model.nombrePersona">
            <label>Primer Apellido:</label>
            <input type="text" class="opacity" readonly value="@Model.apellidoPersona">
            <label>Fecha de Nacimiento: </label>
            <input type="text" class="opacity" readonly value="@(Model.fechaNacPersona == null || Model.fechaNacPersona == " " ? " Sin registrar" :  Convert.ToDateTime(Model.fechaNacPersona).ToString("dd/MM/yyyy"))">
            <label>Correo Electrónico:</label>
            <input type="text" placeholder="perez99@gmail.com" required asp-for="correo_electronico" value="@Model.correo_electronico">
        </div>
        <div>
            <img id="inicio3" src="~/img/registrar_persona.png" alt="inicio3">
        </div>
       
    </div>
    <div id="iniciocenter">
        <button class="btn gris">Volver</button>
        <button class="btn gris">Modificar</button>
    </div>
</form>

AnimaliaV2-master/AnimaliaV2/Views/Persona/GestionarDonaciones.cshtml
@model List<GestionAdopcionViewModel>
@{
    ViewData["Title"] = "gestionar donaciones";

}
<div id="container_img">
    <div id="inicioTitulo">
        <h1 id="titulo_tenue" class="titulopersona">GESTIÓN DE DONACIONES</h1>
    </div>
</div>

<div id="container_table">
    <table>
        <tr>
            <th>N° de Documento</th>
            <th>Nombre Completo</th>
            <th>Nombre Mascota</th>
            <th>Fecha de la Solicitud</th>
            <th>Acción</th>
            <th>Acción</th>
        </tr>
         @foreach (var item in Model){
        <tr>
            <td>@item.documentoPersona</td>
            <td>@item.Nombre_Completo</td>
            <td>@item.nombreMascota</td>
            <td>@(Convert.ToDateTime(item.fechaSolicitud).ToString("dd-MM-yyyy"))</td>
            <td>
                    <form method="post" asp-action="donarMascota" asp-controller="Persona">
                        <button class="btn morado">Donar</button>
                        <input type="hidden" name="id_solicitud" value="@item.id_Solicitud" />
                        <input type="hidden" name="id_mascota" value="@item.idMascota" />
                    </form>
            </td>
            <td>
                    <form method="post" asp-action="eliminar_solicitud_adopcion" asp-controller="Persona">
                        <button class="btn tenue">Eliminar</button>
                        <input type="hidden" name="id_solicitud" value="@item.id_Solicitud" />
                        <input type="hidden" name="id_mascota" value="@item.idMascota" />
                    </form>
                
            </td>
        </tr>
        }

    </table>
</div>
<div id="container_button">
    <a class="btn morado" asp-action="solicitudes" asp-controller="Persona">Volver</a>
    <label></label>
</div>

AnimaliaV2-master/AnimaliaV2/Views/Persona/GestionarSolicitudes.cshtml
@model List<GestionarSolicitudViewModel>
@{
    var autonumerico = 1;
    ViewData["Title"] = "gestionar solicitudes";
    
}
<div id="container_colum">
    <div id="inicioTitulo">
        <h1 id="titulo_azul" class="tamaniotitulo">GESTIÓN DE SOLICITUDES</h1>
    </div>
    <div>
        <img id="inicio4" src="~/img/solicitud.png" alt="inicio4">
    </div>
</div>

    <div id="container_table">
        <table class="AnchoTable">
            <tr>
                <th>ID</th>
                <th>Nombre del Animal</th>
                <th>Estado</th>
                <th>Nombre Completo</th>
                <th>Teléfono</th>
                <th>Acciones</th>
            </tr>
            @foreach (var item in Model){
            <tr>
                <td>@autonumerico</td>
                <td>@item.nombreMascota</td>
                <td>@item.estado_Solicitud</td>
                <td>@item.Nombre_Completo</td>
                <td>@item.telefono</td>

                <td>
                    <div>
                        <form method="post" asp-action="denegarSolicitud" asp-controller="Persona">
                        <button class="btn rojo">Denegar</button>
                        <input type="hidden" name="id_denegar" value="@item.id_solicitud" />
                        </form>
                    
                        <form method="post" asp-action="AprobarSolicitud" asp-controller="Persona">
                        <button class="btn azul">Aprobar</button>
                        <input type="hidden" name="id_aprobar" value="@item.id_solicitud" />
                         <input type="hidden" name="id_mascota" value="@item.id_mascota" />
                        </form>
                     </div>
                 </td>
            </tr>
                autonumerico++;
            }
           
        </table>

    </div>

    <div id="container_button">
    <a class="btn rojo" asp-action="solicitudes" asp-controller="Persona">Volver</a>
        <label></label>
    </div>

AnimaliaV2-master/AnimaliaV2/Views/Persona/ListadoPersonas.cshtml
@model  List<PersonaModel>
@{
    ViewData["Title"] = "Listado de Personas";

}
<div id="container_img">
    <div>
        <img id="img5" src="~/img/hombre.png" alt="img5">
    </div>
    <div id="inicioTitulo">
        <h1 id="titulo_tenue" class="titulopersona">LISTADO DE PERSONAS</h1>
    </div>
    <div>
        <img id="img5" src="~/img/mujer.png" alt="img5">
    </div>
</div>

<div id="container_table">
    <table class="AnchoTable2">
        <tr>
            <th>N° documento</th>
            <th>Nombre Completo</th>
            <th>Fecha de Nacimiento</th>
            <th>Dirección</th>
            <th>Correo</th>
            <th>Opción</th>
        </tr>
         @foreach (var item in Model){
        <tr>
            <td>@item.documentoPersona</td>
            <td>@item.nombrePersona</td>
                <td>@(Convert.ToDateTime(item.fechaNacPersona).ToString("dd-MM-yyyy"))</td>
            <td>@item.direcccion</td>
            <td>@item.correo_electronico</td>
            <td>
                    <form method="post" asp-action="EditarPersona" asp-controller="Persona">
                        <button class="btn verde">Editar</button>
                        <input type="hidden" name="id_persona" value="@item.idPersona" />
                    </form>
               
            </td>
        
        </tr>
        }

    </table>
</div>
<div id="container_button">
    <a class="btn gris" asp-action="gestionarPersonas" asp-controller="Persona">Volver</a>

</div>

AnimaliaV2-master/AnimaliaV2/Views/Persona/ListadoUsuarios.cshtml
@model List<UsuarioViewModel>
@{
    var autonumerico = 1;
    ViewData["Title"] = "Listado de Personas";

}
<div id="container_img">
    <div>
        <img id="img5" src="~/img/hombre.png" alt="img5">
    </div>
    <div id="inicioTitulo">
        <h1 id="titulo_tenue" class="titulopersona">LISTADO DE USUARIOS</h1>
    </div>
    <div>
        <img id="img5" src="~/img/mujer.png" alt="img5">
    </div>
</div>

<div id="container_table">
    <table>
        <tr>
            <th>Id</th>
            <th>Nombre</th>
            <th>Contraseña</th>
            <th>Rol</th>
            <th>Opción</th>
            <th>Opción</th>
        </tr>
         @foreach (var item in Model){
        <tr>
            <td>@autonumerico</td>
            <td>@item.nombreUsuario</td>
            <td>@item.contraseniaUsuario</td>
            <td>@item.rol</td>
            <td>
                    <form method="post" asp-action="Modificar_Usuario" asp-controller="Persona">
                        <a class="btn verde" href="@Url.Action("Modificar_Usuario", new { id_usuario = item.idUsuario })">Editar</a>
                        <input type="hidden" name="id_usuario" value="@item.idUsuario" />
                    </form>
                
            </td>
            <td>
                    <form method="post" asp-action="Eliminar_Usuario" asp-controller="Persona">
                        <button class="btn rojo">Eliminar</button>
                        <input type="hidden" name="id_usuario" value="@item.idUsuario" />
                    </form>
                
            </td>
            </tr>
            autonumerico++;

        }
    </table>
</div>
<div id="container_button">
    <a class="btn gris" asp-action="gestionarPersonas" asp-controller="Persona">Volver</a>
</div>

AnimaliaV2-master/AnimaliaV2/Views/Persona/MisMascotas.cshtml
@model List<MisMascotasModel>
@{
    var autonumerico = 1;
    ViewData["Title"] = "Mis Mascotas";

}
<div id="inicioTitulo">
    <h1 id="titulo_azul" class="titulopersona">MIS MASCOTAS</h1>
</div>
<div id="container_table">
    <table>
        <tr>
            <th>ID</th>
            <th>Nombre del Animal</th>
            <th>Especie</th>
            <th>Ubicación</th>
            <th>Acción</th>
            <th>Acción</th>
        </tr>
        @foreach (var item in Model){
        <tr>
            <td>@autonumerico</td>
            <td>@item.nombreMascota</td>
            <td>@item.especieMascota</td>
            <td>@item.ubicacion</td>
            <td>
                    <form method="post" asp-action="modificarRegistroMedicoVeterinario" asp-controller="Mascotas">
                       <button class="btn azul">Editar</button>
                        <input type="hidden" name="idRegistro" value="@item.idRegistroMedico" />
                  </form>
            </td>
            <td>
                <form method="post" asp-action="EliminarMascota" asp-controller="Persona">
                       <button class="btn rojo">Eliminar</button>
                        <input type="hidden" name="id_mascota" value="@item.idMascota" />
                  </form>
                
            </td>
        </tr>
            autonumerico++;
        }
    </table>
</div>
<div id="container_button">
    <a class="btn gris" asp-action="solicitudes" asp-controller="Persona">Volver</a>
    <label></label>
</div>

AnimaliaV2-master/AnimaliaV2/Views/Persona/ModificarPersona.cshtml
@model PersonaModel
@{
    ViewData["Title"] = "Datos Personales";

}
<div id="inicioTitulo">
    <h1 id="tituloInicio" class="titulopersona">DATOS PERSONALES</h1>
</div>
<form method="post" asp-action="ModificarPersona" asp-controller="Persona">
    <div id="displayflex">
        <div id="display">
            <input type="hidden" asp-for="idPersona" value="@Model.idPersona">
            <label>Número de Documento:</label>
            <input type="text" class="opacity" readonly value="@Model.documentoPersona">
            <label>Segundo Nombre:</label>
            <input type="text" class="opacity" placeholder="Opcional" readonly value="@Model.snombrePersona">
            <label>Segundo Apellido:</label>
            <input type="text" class="opacity"  placeholder="Opcional" readonly value="@Model.sapellidoPersona">
            <label>Dirección:</label>
            <input type="text" class="opacity" readonly value="@Model.direcccion">
            <label>Teléfono:</label>
            <input type="text" asp-for="telefono" required value="@Model.telefono">
        </div>
        <div id="display">
            <label>Primer Nombre:</label>
            <input type="text" class="opacity" readonly value="@Model.nombrePersona">
            <label>Primer Apellido:</label>
            <input type="text" class="opacity" readonly value="@Model.apellidoPersona">
            <label>Fecha de Nacimiento: </label>
            <input type="text" class="opacity" readonly value="@(Model.fechaNacPersona == null || Model.fechaNacPersona == " " ? " Sin registrar" :  Convert.ToDateTime(Model.fechaNacPersona).ToString("dd/MM/yyyy"))">
            <label>Correo Electrónico:</label>
            <input type="text" placeholder="perez99@gmail.com" required asp-for="correo_electronico" value="@Model.correo_electronico">
        </div>
        <div>
            <img id="inicio3" src="~/img/registrar_persona.png" alt="inicio3">
        </div>
    </div>
    <div id="iniciocenter">
        <button class="btn gris">Modificar</button>
    </div>
</form>

AnimaliaV2-master/AnimaliaV2/Views/Persona/Modificar_Usuario.cshtml
@model UsuarioViewModel
@{
    ViewData["Title"] = "Modificar usuario";
}
<div id="inicioTitulo">
    <h1 id="tituloInicio" class="titulopersona">MODIFICAR USUARIO</h1>
</div>
<form method="post" asp-action="Modificar_Usuario" asp-controller="Persona">
    <div id="displayborder">
        <div id="container_img">
            <img id="inicio4" src="~/img/adoptar.png" alt="inicio4">
        </div>
        <div id="display_row">
            <div id="displaycolum">
                <label>NOMBRE DE USUARIO:</label>
                <label>CONTRASEÑA:</label>
              
            </div>
            <div id="displaycolum">
                <input class="opacity" readonly type="text" value="@Model.nombreUsuario" asp-for="nombreUsuario">
                <input type="text" value="@Model.contraseniaUsuario" asp-for="contraseniaUsuario">
                <input type="hidden" value="@Model.idUsuario" asp-for="idUsuario">
            </div>
        </div>
        <div id="container_button">
            <button type="button" onclick="history.back()" class="btn gris">Volver</button>
            <button  class="btn gris">Modificar</button>
        </div>
    </div>
</form>

AnimaliaV2-master/AnimaliaV2/Views/Persona/gestionarPersonas.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1 class="titulo" id="tituloInicio">Gestionar Personas</h1>
<div class="contenedorGestionarPersonas" style="margin-top: 7rem;">
    <a class="gestionarPersonas" asp-action="listadoUsuarios" asp-controller="Persona">
        <img id="imgGestionarMascotas" src="~/img/personas.png" alt="">
        <span><strong>Lista de usuarios</strong></span>
    </a>
    <a class="gestionarPersonas" asp-action="ListadoPersonas" asp-controller="Persona">
        <img id="imgGestionarMascotas" src="~/img/empleados.png" alt="">
        <span><strong>Lista de personas</strong></span>
    </a>
</div>

AnimaliaV2-master/AnimaliaV2/Views/Persona/misSolicitudes.cshtml
@model List<SolicitudAdopcionViewModel>
@{
    var autonumerico = 1;
    ViewData["Title"] = "mis solicitudes";
}
<div id="container_colum">
    <div id="inicioTitulo">
        <h1 id="titulo_azul" class="tamaniotitulo">MIS SOLICITUDES</h1>
    </div>
    <div>
        <img id="inicio4" src="~/img/adoption.png" alt="inicio4">
    </div>
</div>
<form method="post" asp-action="eliminarSolicitud" asp-controller="Persona">
    <div id="container_table">
        <table>
            <tr>
                <th>ID</th>
                <th>Nombre del Animal</th>
                <th>Especie</th>
                <th>Estado</th>
                <th>Ubicación de la Mascota</th>
                <th>Acciones</th>
            </tr>
            
            @foreach (var item in Model){
            
            <tr>
                <td>@autonumerico</td>
                <td>@item.nombreMascota</td>
                <td>@item.especieMascota</td>
                <td>@item.estado_Solicitud</td>
                <td>@item.ubicacionMascota</td>
                <td>
                    <button class="btn rojo">Cancelar</button>
                        <input type="hidden" name="id" value="@item.idSolicitudAdopcion" />
                </td>
            </tr> 
                autonumerico++;
            }
        </table>
    </div>
</form>
    <div id="container_button">
    <a class="btn gris" asp-action="solicitudes" asp-controller="Persona">Volver</a>
        <label></label>
    </div>

AnimaliaV2-master/AnimaliaV2/Views/Persona/solicitudes.cshtml
@{
}


<h1 class="titulo" id="tituloInicio">Solicitudes</h1>
<div class="contenedorGestionarPersonas">
    <a class="gestionarPersonas" asp-action="misSolicitudes" asp-controller="Persona">
        <img id="imgGestionarMascotas" src="~/img/gatoCaja.png" alt="">
        <span><strong>Mis solicitudes</strong></span>
    </a>
    <a class="gestionarPersonas" asp-action="GestionarSolicitudes" asp-controller="Persona">
        <img id="imgGestionarMascotas" src="~/img/solicitud.png" alt="">
        <span><strong>Gestion de solicitudes</strong></span>
    </a>
</div>
<div class="contenedorGestionarPersonas">
    <a class="gestionarPersonas" asp-action="misMascotas" asp-controller="Persona">
        <img id="imgGestionarMascotas" src="~/img/perro-delante-de-un-hombre.png" alt="">
        <span><strong>Mis mascotas</strong></span>
    </a>
    <a class="gestionarPersonas" asp-action="GestionarDonaciones" asp-controller="Persona">
        <img id="imgGestionarMascotas" src="~/img/donacion.png" alt="">
        <span><strong>Gestion de donaciones</strong></span>
    </a>
</div>